#
# Noctalia Behaviours
# 

# ==== Shell Behaviours ====

[shell]
niri_overview_type_to_launch_enabled = true

[nightlight]
enabled           = true
temperature_day   = 6500
temperature_night = 3500

[battery]
warning_threshold = 20

[notification]
history_retention_hours = 168   # 7 days

[lockscreen]
lock_before_suspend  = true
allow_empty_password = true


# ==== Session Controls ====

# Countdown guards to prevent fat fingering.

[[shell.session.actions]]
action   = "lock"
shortcut = "1"

[[shell.session.actions]]
action   = "logout"
shortcut = "2"
countdown_seconds = 3.0

[[shell.session.actions]]
action   = "lock_and_suspend"
shortcut = "3"
countdown_seconds = 3.0

[[shell.session.actions]]
action   = "reboot"
shortcut = "4"
countdown_seconds = 3.0

[[shell.session.actions]]
action   = "shutdown"
shortcut = "5"
variant  = "destructive"
countdown_seconds = 3.0


# ==== Idle ====

# Lock 15m, screen off 30m, suspend 1h.

[idle]
behavior_order = ["lock", "screen-off", "suspend"]
pre_action_fade_seconds = 5.0

[idle.behavior.lock]
timeout = 300
action = "lock"

[idle.behavior.screen-off]
timeout = 600
action = "screen_off"

[idle.behavior.suspend]
timeout = 1200
action = "suspend"
lock_before_suspend = true
